[project]
name = "cvault-backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.30.0",
    "groq>=0.11.0",
    "pypdf>=4.3.0",
    "python-multipart>=0.0.9",
    "python-dotenv>=1.0.0",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
    "llama-index-core>=0.12.0",
    "llama-index-llms-groq>=0.3.0",
    "aiosqlite>=0.20.0",
    "chromadb>=0.4.0",
    "torch",
    "sentence-transformers>=2.7.0",
]

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
